// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrKiplqM3XRlex2PaXTBgmlqHBQ8EKkE',
    appId: '1:564446348138:web:a541525d2ecdcf9e8f1b13',
    messagingSenderId: '564446348138',
    projectId: 'thecodyapp-backend-5c088',
    authDomain: 'thecodyapp-backend-5c088.firebaseapp.com',
    storageBucket: 'thecodyapp-backend-5c088.appspot.com',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeQUjM4BTzfHbDSsHIVzGsZW827p79lJE',
    appId: '1:564446348138:android:4972e6324502f79e8f1b13',
    messagingSenderId: '564446348138',
    projectId: 'thecodyapp-backend-5c088',
    storageBucket: 'thecodyapp-backend-5c088.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpf4IX2hTe9ZFf5i5rTYrSUgJiM2Abqt4',
    appId: '1:564446348138:ios:addb742e8b9611048f1b13',
    messagingSenderId: '564446348138',
    projectId: 'thecodyapp-backend-5c088',
    storageBucket: 'thecodyapp-backend-5c088.appspot.com',
    iosClientId:
        '564446348138-bapcdn5q5fobqvvk9f611uhse497el8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.thecodyapp',
  );
}
